[tool.poetry]
name = "aush"
version = "0.3.0"
description = "Pythonic subprocess library"
authors = ["Keith Devens"]
repository = "https://github.com/kbd/aush"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"
mypy = "^0.812"
pylint = "^2.8.2"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
